name: Build Resume PDF
on:
  push:
    branches:
      - main
    paths:
      - 'main.tex'
      - 'gitassets/certification/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: "-pdf -interaction=nonstopmode -shell-escape"
          extra_system_packages: "inkscape librsvg"

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume-Mohammad-Yehya
          path: main.pdf
