name: Build Resume PDF
on:
  push:
    branches:
      - main
    paths:
      - 'main.tex'
      - 'gitassets/certification/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: "-pdf -interaction=nonstopmode -shell-escape"
          extra_system_packages: "inkscape librsvg"

      - name: Release Latest PDF
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          name: Latest Resume Build
          files: main.pdf
          draft: false
          prerelease: false
          body: |
            Automated build of Mohammad Yehya Hayati's Resume.
            Generated on ${{ github.event.head_commit.timestamp }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
